# Generated by Django 4.2.1 on 2023-05-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_customuser_recv_reports_customuser_tgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='recv_reports',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tgid',
        ),
    ]
