# Generated by Django 4.2.1 on 2023-05-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_remove_customuser_recv_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='send_reports',
            field=models.BooleanField(default=False, verbose_name='отправлять отчёты'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tgid',
            field=models.BigIntegerField(null=True, verbose_name='телеграм ID'),
        ),
    ]
