# Generated by Django 4.2.1 on 2023-05-18 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot_app', '0009_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_confirmation', models.ImageField(upload_to='confirmations/', verbose_name='фото подтверждение')),
                ('img_hash', models.CharField(max_length=100, null=True, verbose_name='хеш подтверждения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='выполнена')),
                ('out_of_time', models.BooleanField(default=False, verbose_name='доступно для выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('completed_at', models.DateTimeField(null=True, verbose_name='время выполнения')),
                ('task_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot_app.tasktype', verbose_name='задача')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tgbot_app.worksession', verbose_name='смена')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_perfect', models.BooleanField(default=True)),
                ('unfulfilled_tasks', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot_app.store')),
            ],
        ),
    ]
