# Generated by Django 4.2.1 on 2023-05-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='tasks_cnt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='unfulfilled_tasks',
            field=models.TextField(blank=True),
        ),
    ]
