# Generated by Django 4.2.1 on 2023-05-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
            ],
            options={
                'verbose_name': 'торговая точка',
                'verbose_name_plural': 'торговые точки',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('need_confirmation', models.BooleanField(verbose_name='подтверждение')),
                ('time_exec', models.CharField(choices=[('morning', 'утро'), ('midday', 'обед'), ('evening', 'вечер'), ('all_day', 'весь день')], max_length=10, verbose_name='время выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('tgid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='телеграм ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(auto_now_add=True, verbose_name='начало смена')),
                ('close_time', models.DateTimeField(null=True, verbose_name='окончание смены')),
                ('comment', models.TextField(blank=True, verbose_name='комментарии')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot_app.store', verbose_name='торговая точка')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot_app.worker', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'смена',
                'verbose_name_plural': 'смены',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_confirmation', models.ImageField(upload_to='confirmations/', verbose_name='фото-подтверждение')),
                ('img_hash', models.CharField(max_length=100, null=True, verbose_name='хеш подтверждения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='выполнена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('completed_at', models.DateTimeField(null=True, verbose_name='время выполнения')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tgbot_app.worksession', verbose_name='смена')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='tasks',
            field=models.ManyToManyField(to='tgbot_app.tasktype', verbose_name='задачи'),
        ),
    ]
