# Generated by Django 4.2.1 on 2023-05-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задание', 'verbose_name_plural': 'задании'},
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot_app.tasktype', verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img_confirmation',
            field=models.ImageField(upload_to='confirmations/', verbose_name='фото подтверждение'),
        ),
    ]
