# Generated by Django 4.2.1 on 2023-05-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0003_alter_task_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='tasks',
            new_name='task_types',
        ),
    ]
