# Generated by Django 4.2.1 on 2023-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0004_rename_tasks_store_task_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='доступно для выполнения'),
        ),
    ]
