# Generated by Django 4.2.1 on 2023-05-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0005_task_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_open',
        ),
        migrations.AddField(
            model_name='task',
            name='out_of_time',
            field=models.BooleanField(default=False, verbose_name='доступно для выполнения'),
        ),
    ]
