# Generated by Django 4.2.1 on 2023-05-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0006_remove_task_is_open_task_out_of_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='открыта'),
        ),
    ]
