# Generated by Django 4.2.1 on 2023-05-18 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0007_worksession_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='close_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время закрытия торговой точки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='midday_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='крайнее время для дневных задач'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='morning_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='крайнее время для утренних задач'),
            preserve_default=False,
        ),
    ]
