# Generated by Django 4.2.1 on 2023-05-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0008_store_close_time_store_midday_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
