# Generated by Django 4.2.1 on 2023-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0010_alter_tasktype_need_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
    ]
