# Generated by Django 4.2.1 on 2023-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0011_alter_tasktype_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('tgid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='телеграм ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'администратор',
                'verbose_name_plural': 'администраторы',
            },
        ),
    ]
